# Generated by Django 5.2 on 2025-10-26 12:47

import auth_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_authtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=auth_app.models.AuthToken.get_default_expiry, help_text='Token expiration time (defaults to 24 hours from creation)'),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='authtoken',
            index=models.Index(fields=['user', 'purpose'], name='auth_tokens_user_id_42b305_idx'),
        ),
        migrations.AddIndex(
            model_name='authtoken',
            index=models.Index(fields=['expires_at'], name='auth_tokens_expires_f09206_idx'),
        ),
        migrations.AlterModelTable(
            name='authtoken',
            table='auth_tokens',
        ),
    ]
