# Generated by Django 5.2 on 2025-11-09 20:29

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_profile_backup_codes_profile_mfa_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=auth_app.models.default_expires_at),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_token',
            field=models.CharField(db_index=True, default=auth_app.models.generate_session_token, max_length=255, unique=True),
        ),
    ]
