# Generated by Django 5.2 on 2025-11-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_usersession_expires_at_alter_usersession_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='backup_codes',
            field=models.JSONField(default=list),
        ),
    ]
