# Generated by Django 5.2 on 2025-11-09 20:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0020_add_due_date_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='members',
        ),
        migrations.RemoveField(
            model_name='card',
            name='watchers',
        ),
        migrations.CreateModel(
            name='CardAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_assignees_made', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees_through', to='boards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_assignees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers_through', to='boards.card')),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_watches_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_watchers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CardMembership',
        ),
        migrations.AddIndex(
            model_name='cardassignee',
            index=models.Index(fields=['card'], name='boards_card_card_id_898bc0_idx'),
        ),
        migrations.AddIndex(
            model_name='cardassignee',
            index=models.Index(fields=['user'], name='boards_card_user_id_4a0516_idx'),
        ),
        migrations.AddIndex(
            model_name='cardassignee',
            index=models.Index(fields=['card', 'user'], name='boards_card_card_id_6870ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cardassignee',
            unique_together={('card', 'user')},
        ),
        migrations.AddIndex(
            model_name='cardwatcher',
            index=models.Index(fields=['card'], name='boards_card_card_id_6b9ecb_idx'),
        ),
        migrations.AddIndex(
            model_name='cardwatcher',
            index=models.Index(fields=['user'], name='boards_card_user_id_808075_idx'),
        ),
        migrations.AddIndex(
            model_name='cardwatcher',
            index=models.Index(fields=['card', 'user'], name='boards_card_card_id_e07115_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cardwatcher',
            unique_together={('card', 'user')},
        ),
    ]
