# Generated by Django 5.2 on 2025-11-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0022_useractivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('board', 'name')},
        ),
        migrations.AddIndex(
            model_name='label',
            index=models.Index(fields=['board', 'name'], name='boards_labe_board_i_ebc03d_idx'),
        ),
    ]
