# Generated by Django 5.2 on 2025-11-30 01:54

import boards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0023_alter_label_options_alter_label_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(max_length=20, validators=[boards.models.validate_hex_color]),
        ),
    ]
