# Generated by Django 5.2 on 2025-12-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0025_alter_label_options_label_created_at_and_more'),
    ]

    operations = [
        
    ]
